### ISSUE TITLE
Logging: add the final configuration 

### ISSUE THREAD

**Issue by plbt5** [htdebeer/pandocomatic#112]
Indeed, pandocomatic can do a lot of things in preparation of the pandoc conversion, as well as in postprocessing of its result(s). To that end, various ways exist in which the configuration can be extended, modified, added or overwritten, using different configuration files each of which carrying various templates. All in all, the end result of all that configuration data is difficult to determine; at least, I cannot tell the tree for the forest anymore.

It would be helpful if pandocomatic would show the concluding configuration that results from all the default, extended and modified configuration files and templates in its log file, separating its own configuration from pandoc's configuration. 

Thanks in advance,
Paul

**Comment by htdebeer** [comment]
That's a great idea. Actually, just adding logging alone would be a good idea. Now your only option is to have a verbose output or not, but opting to log to a file instead might be nice as well.

I'm not sure how easy it is to add good logging, though. Pandocomatic has become a bit of a mess, so I'd need to refactor the code base first. So this will be something for the long run, I'm afraid.

**Comment by htdebeer** [comment]
Added logging to pandocomatic. Pandocomatic now logs what it is doing to file. When using detail level "debug", it logs every step in the conversion process. This includes the
final template used for the conversion, all processors that are run, and
the full pandoc invocation.

To implement this feature, I made the following changes:

- Remove command-line option `--debug` (breaking change). Instead, use
  command-line options `--log` and `--log-level debug`.

- Add command-line option `--log [FILE]`. This tells pandocomatic to log
  its doings to `FILE`. If you don't supply a file, pandocomatic logs to
  "pandocomatic.log" by default.

- Add command-line option `--log-level [LEVEL]`. This tells pandocomatic
  what level of detail to log. Possible values are: "fatal", "error",
  "warning", "info", and "debug". Default value is "info".

  This option only has an effect when used together with command-line
  option `--log`.

  Pick level "debug" for a complete overview of the conversion process.

Because these changes are a breaking change in pandocomatic's
interface, I am preparing a new major version: 2.0. Logging will be available from version 2.0 onwards.

You can already test it by cloning the repository and using `test/pandocomatic.rb` as the pandocomatic executable. Feedback on logging welcome.
