### ISSUE TITLE
Verbose or Debugging line switch?

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#20]
I'm having a problem running (using Open3.popen3) pandocomatic from another script. Pandocomatic does not trigger pandoc, yet returns basically nothing, no stdout, no stderr and an exit status of 0, so I don't really know where things are going wrong. Is there a verbose or debugging mode. Sorry I'm pretty naive with Ruby, so what is the best method to run a local github clone version even if I have a ruby gem installed? Or can I just hack on the ruby gem directory itself, then reinstall to cleanup afterwards?

**Comment by htdebeer** [comment]
I sort of had the same problem with testing the newest code without needing to create and install a new gem each time. To overcome this problem I have created the script `pandocomatic.rb` in the `test` directory. It is the same as the `pandocomatic` executable in the `bin` directory, but it points to the local files instead of the files in the gem. You can use this test executable by, for example:

    /path/to/pandocomatic/test/pandocomatic.rb -c config.yaml -i input.md -o output.html

I have never tried running pandocomatic from another Ruby script. I do run pandocomatic from Bash shell scripts, though.

**Comment by iandol** [comment]
Actually I have a program that I use for all my academic writing, and it compiles to Pandoc output, and can run an external program. BUT the default path is `/usr/bin:/bin:/usr/sbin:/sbin`. Now for Pandoc I can just specify `/usr/local/bin/pandoc` and as long as I use absolute paths for pandoc-citeproc then pandoc runs fine. If I use `/usr/local/bin/pandocomatic -v` then pandocomatic runs fine and I get `STDOUT` version string. But if I actually try to run `/usr/local/bin/pandocomatic -i myfile.md` then I get a silent failure. The problem is that pandocomatic cannot find pandoc yet doesn't seem to trigger an error or warning to STDOUT or STDERR. So I thought OK, I'll write a simple wrapper script [(see it here)](https://github.com/iandol/scrivomatic/blob/master/scrivomatic) to set up the path and then run pandocomatic. But I still get a silent failure. So perhaps `paru` doesn't receive the path, or it is something else in this case. As pandocomatic doesn't output anything, I'll have to add logging to pandocomatic locally. Ideally I would be able to trigger a terminal with `pry` or `byebug` or something, but don't know how that works. As I'm not really a ruby person any tips on debugging would be welcome.

**Comment by htdebeer** [comment]
See [pandoc/pandoc.rb](https://github.com/htdebeer/paru/blob/master/lib/paru/pandoc.rb) for how Paru runs pandoc. It makes a system call to `pandoc with...options` via popen:

```
 def convert input
      output = ""
      IO.popen(to_command, "r+") do |p|
        p << input
        p.close_write
        output << p.read
      end
      output
    end
    alias << convert
```

That should just work in any other script.

The odd thing is, I have added some error reporting when pandocomatic cannot run pandoc for whatever reason. So why isn't that triggered?

Maybe the issue is with (nested) use of [popen](http://ruby-doc.org/core-2.4.1/IO.html#method-c-popen): If I read this correctly, 

> Runs the specified command as a subprocess; the subprocess’s standard input and output will be connected to the returned IO object.

your script runs pandocomatic as a sub process, which then runs pandoc as a sub process. But that should not interfere with finding pandoc, unless it is not in PATH anymore in one of the sub processes. This is something to investigate further.

Personally, I prefer to put `puts` statements to debug so I cannot give any tips with regards to using more "professional" debugging tools. One tip I am able to give: try to create a minimal example. 

For example, what happens if you run one of the example paru scripts, asy [hello_world](https://github.com/htdebeer/paru/blob/master/examples/hello_world.rb) instead of pandocomatic in your scrivomatic script? If that does not work either, the problem might be with paru rather than pandocomatic.

**Comment by htdebeer** [comment]
So, if I run your scrivomatic script like `scrivomatic -i hello.md -o hi.html`, I get the pandocomatic version info. As pandocomatic does not accept STDIO, that makes sense, I suppose.

**Comment by htdebeer** [comment]
Actually it seems to run fine:

```
huub@rover:~/Projects/scrivomatic$ ./scrivomatic -i hello.md -o hi.html -v

=== Scrivomatic V1.0.1 Report @ 2017-05-06 12:47:22 +0200 ===
Working directory: /home/huub/Projects/scrivomatic
=======Input Options:=======
#<Scrivomatic:0x0055ff8b9470b0
 @cmd="/usr/local/bin/pandocomatic -i 'hello.md' -o hi.html",
 @options=
  #<struct Scrivomatic::OPTIONS
   input="hello.md",
   output="hi.html",
   tool="pandocomatic",
   envpath="/usr/local/bin:/home/huub/bin",
   verbose=true>,
 @runLog=
  "::: Will try to run /usr/local/bin/pandocomatic -i 'hello.md' -o hi.html\n::: Pandocomatic needed 0.0 seconds to convert 'hello.md' to 'hi.html'.\n\n::: exit status: pid 5319 exit 0",
 @version="1.0.1">
=======ENV PATH:=======
/usr/local/bin:/home/huub/bin:/home/huub/.cabal/bin:/home/huub/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
=======TOOL PATHS:=======
---ruby: /usr/bin/ruby
---python: /usr/bin/python
---rbenv: 
---pandoc: /home/huub/.cabal/bin/pandoc
---pandocomatic: /usr/local/bin/pandocomatic
---panzer: 
=======TOOL OUTPUT:=======
::: Will try to run /usr/local/bin/pandocomatic -i 'hello.md' -o hi.html
::: Pandocomatic needed 0.0 seconds to convert 'hello.md' to 'hi.html'.

::: exit status: pid 5319 exit 0
```

Is this not the output you'd expect?

**Comment by iandol** [comment]
Yes, when I run scrivomatic from the command line everything works, but the problem comes when run from writing software:

`ProgramX` > $HOME/bin/`hello_world.rb`[paru:popen] == `sh: pandoc: command not found`

`ProgramX` > $HOME/bin/`scrivomatic`[popen3] > `hello_world.rb`[paru:popen] == `<p>Hello world, from <strong>pandoc</strong>`

As I expected, a ruby script that calls paru from ProgramX will fail. My script `scrivomatic` sets up the path and thus `hello_world.rb` now can call paru and pandoc is found.


So I turned to `byebug`. You can set it up to a remote debug session (here I append "DEBUG" to ARGV input to set it up, otherwise it is not called):

```ruby
if ARGV[-1] == 'DEBUG'
  require 'byebug/core' 
  require 'byebug'
  Byebug.wait_connection = true
  Byebug.start_server('localhost', 1048)
  STDOUT.puts "!!!---DEBUG Server started on localhost:1048"
  ARGV.pop
end
```

Wherever you put `byebug` in the ruby code it will hang there. You then use a terminal to `byebug -R localhost:1048` and you enter an interactive debugger. This mean you can debug any ruby process even when it is not running from a shell. Very cool. And I found this:

`ProgramX` > $HOME/bin/`scrivomatic`[popen3] > `/Users/ian/Code/pandocomatic/test/pandocomatic.rb`[paru:popen] == 

```
:: Will try to run /Users/ian/Code/pandocomatic/test/pandocomatic.rb --input "SFV4.md" 
::: Error opening file: invalid byte sequence in US-ASCII.

::: exit status: pid 88008 exit 0
```

If I remove any non-ascii characters from the input file then it works!!! So this is a Ruby "issue", where ascii encoding mode is triggered depending on the launch environment (ENV['LANG']=nil). The error occurs at `command = ConvertFileMultipleCommand.new(configuration, input, destination)`. 

To fix this one can add

```ruby
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
```
https://ruby-doc.org/core-2.0.0/Encoding.html

to the very top of pandocomatic/pandocomatic.rb and it then works. I'm not sure what the downside of forcing pandocomatic into using UTF8, but it shouldn't be a problem? Phew!

**Comment by htdebeer** [comment]
Awesome research work! That was some obscure configuration issue you found. 

I often wonder, in this day and age, why are encodings still a problem? Anyway, thanks for your improvement.

**Comment by iandol** [comment]
Thanks for the quick merge and gem update! Pandoc only accepts UTF input:

>Pandoc uses the UTF-8 character encoding for both input and output. If your local character encoding is not UTF-8, you should pipe input and output through iconv

So there should be no other side effects. And yes UTF8 should be the default everywhere!!! 👺
