### ISSUE TITLE
Allow configuring "skip" per template definition

### ISSUE THREAD

**Issue by agusmba** [htdebeer/pandocomatic#48]
Hi @htdebeer 

When converting markdown to html it makes sense to copy all images to the output directory.
However when converting to docx or odt, which include images in the main output file, the external images don't need to be copied over.

If I configure skip in the setup part of my common pandocomatic.yaml, it will affect all templates.
Would it be possible to also define skip at each template level, so that docx conversion and html conversion can skip different patterns?

Thanks!

**Comment by htdebeer** [comment]
Something like that does make sense. However, conceptually pandocomatic templates are about files rather than documents. When converting directory trees, you can customize the way directories are converted by means of the `pandocomatic.yaml` configuration file in a directory. When entering a directory to convert, pandocomatic first reads and applies the `pandocomatic.yaml` file in that directory. Only then the conversion process is continued. This allows you to skip images on a per directory basis. 

For example you can tell pandocomatic to skip the directory `img` in the `subdirectory` in the `pandocomatic.yaml` file in that subdirectory. Outside the subdirectory, the `pandocomatic.yaml` in the root `src` directory is used.

```
src
+ subdir
   + img
   - doc2.md
   - pandocomatic.yaml
- doc1.md
- pandocomatic.yaml
```

**Comment by agusmba** [comment]
I understand.

The thing is that if you want to convert the same source directory (i.e. markdown with images) to different output formats (docx, html), it would be nice to be able to skip files depending on the template to be applied, not depending on the source directory per se.

From what you say, it's probably not worth it to implement at this stage, since the cost would outweigh the gains (minor/cosmetic)

**Comment by htdebeer** [comment]
Actually, you can do this in a template using the `setup` and `cleanup` sections. In a `setup` section you could adapt the `pandocomatic.yaml` file to skip something or not. Or in the `cleanup` section you could use a script that would remove the copied images again. Scripts in the `setup` section are run before reading the file to convert and scripts in the `cleanup` section are run after the output has been generated and saved to the file system.

**Comment by agusmba** [comment]
Mmm, ok, I think I could make it work with setup and cleanup like you say, if I chose to work only in directory mode, and for different templates I configured different output directories. This way the cleanup script could delete the extra images from the docx directory output, and not from the html one.

Something to think about.

Thanks!

**Comment by htdebeer** [comment]
You could create a template for documents and extend is for directories by adding/extending only the `setup`/`cleanup` sections. That way, you only have to update one template if you want to change the way a document is converted, and it will automatically be used by the "directory" template as well.

**Comment by htdebeer** [comment]
I am closing this issue because conceptually pandocomatic uses templates to setup  the conversion of a file and a pandocomatic configuration file to setup the conversion of a directory. The "skip" directive does not have any meaning when converting files. Therefore, to skip files when converting to docx and not when converting to html users can use different configuration files for generating a directory tree to HTML or docx, one with skipping images and the other not.

As a workaround, a user can also just copy images anyway and use the "cleanup" section of a template to remove the images afterwards. This solution is a bit of a hack, though.

However, for a new version of pandocomatic it might be a good idea to look into the differences between converting files and converting directory trees. Furthermore, the feature of converting a directory tree is now more of an afterthought I added because I wanted to use pandocomatic as a static-site generator. I never thought of converting a tree to other formats than HTML. 

I have created a [wiki page to collect ideas for version 0.3 of pandocomatic](https://github.com/htdebeer/pandocomatic/wiki/Roadmap-for-V0.3). Feel free to extend that page.
