### ISSUE TITLE
pandocomatic 0.2.7.4 build failure

### ISSUE THREAD

**Issue by chenrui333** [htdebeer/pandocomatic#89]
👋 trying to keep pandocomatic up to date, but run into some test step issue with the latest release. Here is the error log.

```
==> /usr/local/Cellar/pandocomatic/0.2.7.4/bin/pandocomatic -i test.md -o test.html
/usr/local/Cellar/pandocomatic/0.2.7.4/libexec/gems/paru-0.4.2.1/lib/paru/pandoc.rb:238:in `<class:Pandoc>': undefined method `[]' for nil:NilClass (NoMethodError)
```

relates to https://github.com/Homebrew/homebrew-core/pull/64247

**Comment by htdebeer** [comment]
It might be an issue with incompatible versions of pandoc + pandocomatic + paru. Can you try to upgrade pandoc to 2.11.1 and make sure paru has version 0.4.2.1 and see if that resolves anything?

**Comment by jmablog** [comment]
I'm also encountering this error. I'm on pandoc 2.11.1.1 and paru 0.4.2.1.

**Comment by htdebeer** [comment]
I have trouble reproducing the issue. Can you send me the output of "pandoc -v"? Because I am parsing that version string and I am assuming it is the same everywhere. But maybe some differences per operating system or environment have been introduced, and that'll crash paru. 

Furthermore, I can make it more robust, but that also means that if things go awry with the version string on someone's system, the behavior of paru might change without much notice.

**Comment by jmablog** [comment]
Apologies; despite thinking I was on the latest pandoc release, my system was still finding an old version hiding away somewhere and running that instead of the latest. I fixed that and everything seems to be working now.

**Comment by chenrui333** [comment]
no longer an issue for me, I have built `pandocomatic 0.2.7.4` along with [pandoc 2.11](https://github.com/Homebrew/homebrew-core/pull/62771).

Thus closing the issue, thanks all!
